### PR TITLE
Add support for composer/installers 2.0

### PR DESCRIPTION
**Pull request by nlemoine**

### CODE REVIEW

**Review by nlemoine — COMMENTED** [review]
Add support for composer/installers ^2.0

**Review by tomjn — CHANGES_REQUESTED** [review]
Looks good but the `composer.lock` file needs updating for this to work

**Comment by tomjn** [comment]
`composer update composer/installers` should be enough to update the lock file without updating other dependencies

**Comment by nlemoine** [comment]
Sure, I didn't see you're adding `composer.lock` to the repo. I'll  also submit a PR in `humanmade/asset-loader` to also support `composer/installers` version 2

**Comment by nlemoine** [comment]
Can you merge this first? 
- https://github.com/humanmade/asset-loader/pull/50

So `authorship` can actually update to `composer/installers` version 2.

**Comment by nlemoine** [comment]
`composer.lock` is updated on both PR. Quick question: why committing this file? It's usually discouraged.

**Comment by tomjn** [comment]
I've pushed out v0.6.3 of asset loader

**Comment by tomjn** [comment]
> `composer.lock` is updated on both PR. Quick question: why committing this file? It's usually discouraged.

I'm not 100% sure as I wasn't around when the decision was made, but I suspect it's related to it also being released on wordpress.org

**Comment by nlemoine** [comment]
> I suspect it's related to it also being released on wordpress.org

Thanks for your feedback. If your composer constraints are confidently set, this shouldn't be a problem removing it. 

I updated both `humanmade/asset-loader` and `composer/installers`.

**Review by tomjn — APPROVED** [review]

**Pull request merged**
