### PR TITLE
Add PHP8 support for composer install

### LINKED ISSUE #74: Consider adding PHP8 to the Composer PHP version constraint
It'd be great to see this updated to allow installation on PHP8 environments (without resorting to `--ignore-platform-reqs`). Tested in our PHP 8 environment and it looks great!

`"php": "~7.2 || ~8.0"` should do the trick.

### PR DESCRIPTION
**Pull request by JayWood**
This adds the PHP 8 info that Chris mentions in the issue. This also bumps PHP Unit to 9.5 which supports PHP8.

Fixes #74

### CODE REVIEW

**Comment by JayWood** [comment]
Grr, looks like something borked on the testing side, will review and update 😞

**Comment by johnbillion** [comment]
Pretty sure you'll need to stick with PHPUnit 7, WP doesn't support 8 or 9. Info: https://make.wordpress.org/core/handbook/references/phpunit-compatibility-and-wordpress-versions/

**Comment by JayWood** [comment]
Yep, will give this a look after work today ( or if I catch a break ) and update. I only bumped it because it complained vigorously when I ran `composer test` - otherwise I would've left it alone entirely. Ty for the Doc link as well.

**Comment by JayWood** [comment]
@johnbillion I've reverted the phpunit back to `^7` but in order to get compose to install locally I had to `--ignore-platform-reqs` still - so I'm not entirely sure that will help us but maybe it will at least let tests pass?

**Comment by chrisvanpatten** [comment]
@johnbillion @JayWood sounds like maybe we should wait for https://core.trac.wordpress.org/ticket/46149 to land?

**Comment by johnbillion** [comment]
Superceded by #98

**Pull request closed without merging**
