### PR TITLE
WP authors migration command - post type argument. 

### PR DESCRIPTION
**Pull request by mattheu**
The recently added wp authors migration command uses query_posts, but does  not provide a way to query multiple post types. 

New param defaults to just posts, but supports passing another post type, or comma separated list of post types. 

e.g. 
```sh
wp authorship migrate wp-authors // default post
wp authorship migrate wp-authors --post-type=page
wp authorship migrate wp-authors --post-type=post,page
```

### CODE REVIEW

**Review by mikelittle — CHANGES_REQUESTED** [review]
The code looks good. 
But there should probably be one or more tests for this new functionality. I'd suggest testing:
1. the default value works
2. posts and pages work
3. maybe a cpt too

**Comment by mattheu** [comment]
Hey @mikelittle - digging up an old pull request here! But the need for this functionality came up again. 

We don't have any precedence in the Authorship plugin for writing tests against CLI command functionaltiy... so I did something very basic by calling the function directly and verifying the data changed as expected. 

To the cases you suggest...
1. default - as I'm calling the function directly, the default is not set. But can re-create by passing `post`
2. Posts and pages. This is passed as comma separated string, so a case I reckon we should test for. 
3. CPT. I actually don't think this is necessary and a bit of a hassle to register a CPT etc.

**Review by mikelittle — APPROVED** [review]
I couldn't get the tests to run in my brief attempt at a local set up, but it all looks good to me.

**Comment by mattheu** [comment]
Ha me neither. I didn’t really try TBH, I just relied on the CI to run them!

**Comment by mikelittle** [comment]
All the tests passed. (though they were marked risky because of the output).

**Pull request merged**
