### PR TITLE
Remove redundant PHPStan config lines

### PR DESCRIPTION
**Pull request by szepeviktor**
From https://github.com/johnbillion/args/pull/7#issuecomment-855484516

### CODE REVIEW

**Comment by szepeviktor** [comment]
@johnbillion It does not start :(

**Comment by szepeviktor** [comment]
AFAIK These are **real** problems.

**Comment by johnbillion** [comment]
I remember the reason for these `scanFiles` entries now. `plugin.php` handles the file loading with `require_once` calls, so PHPStan needs to be told about which files are loaded. The use of the `GUEST_ROLE` and `TAXONOMY` constants are correct.

If those files are removed from `scanFiles` then PHPStan no longer knows they're loaded and triggers those errors.

**Comment by szepeviktor** [comment]
> so PHPStan needs to be told about which files are loaded

Why does not PHPStan triggers those errors in CI? https://github.com/humanmade/authorship/pull/82/files

**Comment by szepeviktor** [comment]
I see! Those constants come from `scanFiles`.

**Pull request closed without merging**
